### Create Order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "customer_id": 1,
  "order_date": "2023-09-16T08:00:00Z",
  "total_price": 123,
  "queue_number": 2,
  "status": "processing",
  "cancel_status": "ยังไม่คืนเงิน"
}

### Get All Orders
GET http://localhost:3000/orders

### Get Order by ID
GET http://localhost:3000/orders/11

### Update Order
PATCH http://localhost:3000/orders/11
Content-Type: application/json

{
  "status": "completed"
}

### Delete Order
DELETE http://localhost:3000/orders/11
