### Create Order
POST http://localhost:3000/employee/orders
Content-Type: application/json

{
  "customer_id": 123,
  "order_date": "2023-09-18T08:00:00Z",
  "total_price": 500,
  "queue_number": 3,
  "status": "processing",
  "cancel_status": "ยังไม่คืนเงิน"
}

### Get All Orders
GET http://localhost:3000/employee/orders

### Get Order by ID
GET http://localhost:3000/employee/orders/12

### Update Order
PATCH http://localhost:3000/employee/orders/10
Content-Type: application/json

{
  "status": "cancel"
}

### Delete Order
DELETE http://localhost:3000/employee/orders/1


PATCH http://localhost:3000/employee/orders/15/cancel
Content-Type: application/json
{
  "order_id": 15,
  "customer_name": "John Doe",
  "contact": "123456789"
}

### Get Order Item 
GET http://localhost:3000/employee/orders/item