POST http://localhost:3000/sweetness-levels
Content-Type: application/json

{
  "level_name": "หวาน 100%",
  "menu_id": 24
}


GET http://localhost:3000/sweetness-levels


GET http://localhost:3000/sweetness-levels/menu/24


DELETE http://localhost:3000/sweetness-levels/1
