
POST http://localhost:3000/sizes/24
Content-Type: application/json

{
  "size_name": "ใหญ่",
  "size_price": 10.00
}

GET http://localhost:3000/sizes


GET http://localhost:3000/sizes/1

DELETE http://localhost:3000/sizes/1
