POST http://localhost:3000/toppings
Content-Type: application/json

{
  "topping_name": "ไข่มุก",
  "price": 10.00
}


GET http://localhost:3000/toppings


GET http://localhost:3000/toppings/1


PATCH http://localhost:3000/toppings/1
Content-Type: application/json

{
  "price": 15.00
}

DELETE http://localhost:3000/toppings/1
