### Register New Owner
POST http://localhost:3000/owners/register
Content-Type: application/json

{
  "owner_name": "John Doe",
  "contact_info": "123456789",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Login Owner
POST http://localhost:3000/owners/login
Content-Type: application/json

{
  "email": "pos@gmail.com",
  "password": "password123"
}

### Upload CSV with Owner Data
POST http://localhost:3000/owners/upload-csv
Content-Type: multipart/form-data

file=@./uploads/owners.csv



### Reset Password
PATCH http://localhost:3000/owners/reset-password/1
Content-Type: application/json

{
  "newPassword": "12345password"
}

