### Register New Owner
POST http://localhost:3000/owners/register
Content-Type: application/json

{
  "owner_name": "John Doe",
  "contact_info": "123456789",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Login Owner
POST http://localhost:3000/owners/login
Content-Type: application/json

{
  "email": "eoeo@pos.com",
  "password": "sssdaaadad"
}

POST http://localhost:3000/owners/forgot-password
Content-Type: application/json
{
  "usernameOrEmail": "eoeo@pos.com"
}
### Upload CSV with Owner Data
POST http://localhost:3000/owners/upload-csv
Content-Type: multipart/form-data

POST http://localhost:3000/owners/verify-otp
Content-Type: application/json
{
  "usernameOrEmail": "eoeo@pos.com",
  "otp": "890121"
}
file=@./uploads/owners.csv

POST http://localhost:3000/owners/reset-password
Content-Type: application/json
{
  "usernameOrEmail": "eoeo@pos.com",
  "newPassword": "sssdaaadad"
}







### Reset Password
PATCH http://localhost:3000/owners/reset-password/1
Content-Type: application/json

{
  "newPassword": "12345password"
}

